### ISSUE TITLE
Please use relative path

### ISSUE THREAD

**Issue by 2926295173** [ALEX5402/NewBlackbox-old#8]
https://github.com/ALEX5402/NewBlackbox/blob/d318afebf0723b277ddc5f85e985ed4add3ecf59/Bcore/build.gradle.kts#L9C27-L9C27

```
storeFile = file("${rootDir}/app/vcore.jks")
```

**Comment by ALEX5402** [comment]
> https://github.com/ALEX5402/NewBlackbox/blob/d318afebf0723b277ddc5f85e985ed4add3ecf59/Bcore/build.gradle.kts#L9C27-L9C27
> 
> ```
> storeFile = file("${rootDir}/app/vcore.jks")
> ```

should be fixed in next commit
